feat: port media input component to zui
zer0-os/zUI pull request #25
Opened 2022-08-27 23:29 UTC by ashmidgley

[Port Media Component into zUI](https://www.notion.so/rational-nomads/Port-Media-Component-into-zUI-56a6a91909ed446d91cfb1b487b74bcb)

-----

## 1. Pull request checklist
- [x] Notion card has been moved to the Code Review column
- [x] Notion card has a link to this PR
- [x] A reviewer has been assigned to the Notion card

## 2. PR type
```
- Feature
```

## 3. What is the old behaviour?
No Media Input component available in zUI.

## 4. What is the new behaviour?
Media Input component added with stories and relevant tests.

2022-08-30 04:05 UTC, colbr requested changes
Looking good, nice job! Few requested changes but nothing crazy.

2022-08-30 04:05 UTC, colbr commented on src/components/MediaInput/MediaInput.test.tsx
> +  expect(container.querySelector('img')).toBeVisible();
Can we also assert that the `img` `src` is `previewUrl` (same for the video one below)?

2022-08-30 04:05 UTC, colbr commented on src/components/MediaInput/MediaInput.tsx
> +  const openUploadDialog = () => (inputFile.current ? inputFile.current.click() : null);
nit: curly braces here, and change to `inputFile.current?.click()`

2022-08-31 23:53 UTC, ashmidgley commented
Cheers for the review @colbr! Great calls all round. Have pushed changes to address the above.

2022-09-04 23:51 UTC, colbr reviewed
🚀

As discussed, change that `input.tsx` to `input.ts` and we're good!

2022-09-05 00:32 UTC, colbr approved these changes
🚀

2022-09-05 00:33 UTC, merged