feat: additional token launcher components
zer0-os/zUI pull request #27
Opened 2022-09-04 23:59 UTC by ashmidgley

[Wizard setup](https://www.notion.so/rational-nomads/Wizard-setup-e89ce4c065004ea09ee3d789db4b9341)

-----

## 1. Pull request checklist
- [x] Notion card has been moved to the Code Review column
- [x] Notion card has a link to this PR
- [x] A reviewer has been assigned to the Notion card

## 2. PR type
```
- Feature
```

## 3. What is the old behaviour?
Missing a few components and some behaviour in existing components required for the Token Launcher project.

## 4. What is the new behaviour?
Addition of the InfoTooltip, cross and question mark icons and tweaks to Wizard Header to allow rendering of children.

2022-09-08 10:50 UTC, colbr requested changes
Looks great! These will need tests, but since they're not going into a production app for a while I'll let them through.

Only required changes are the `px` -> `rem` ones, and running Prettier. Nice work 🚀

2022-09-08 10:50 UTC, colbr commented on src/components/Icons/icons/IconCross.tsx
> +import type { FC } from 'react';
Nice - thanks for adding these! Just FYI we're about to add a script which automatically creates React components from all Figma icons 🚀

2022-09-08 10:50 UTC, colbr commented on src/components/InfoTooltip/InfoTooltip.scss
> +    height: 16px;
Switch these to `1rem`.

2022-09-08 10:50 UTC, colbr commented on src/components/MediaInput/MediaInput.scss
> +        font-size: 14px;
Switch both `font-size`s to `rem` values.

2022-09-08 10:50 UTC, colbr commented on src/components/MediaInput/index.ts
> +export * from "./MediaInput.types";
Not quite sure why there's a `"` and a `'` - do you have prettier running? This reminds me, we should add a Prettier pre-commit hook 😎

2022-09-10 04:40 UTC, ashmidgley commented
Cheers for the review @colbr! Must have let a rogue `npx prettier --write .` slip in there. Should be all sorted now!

2022-09-12 23:50 UTC, colbr approved these changes

2022-09-13 00:32 UTC, merged