feat(dropdown): add dropdown header
zer0-os/zUI pull request #86
Opened 2023-02-16 20:44 UTC by alejoviola

[Associated Notion Card](https://www.notion.so/rational-nomads/Add-header-to-Dropdown-27fe8a91822f4e17a112b5fd112f8536?pvs=4)

-----

## 1. Pull request checklist

- [x] Notion card has been moved to the Code Review column
- [x] Notion card has a link to this PR
- [x] A reviewer has been assigned to the Notion card

## 2. PR type
- Feature

## 3. What is the old behaviour?
- DropdownMenu component doesn't have a header and children support.

## 4. What is the new behaviour?
- Create DropdownHeader component to be put inside DropdownMenu.
- Add children support on DropdownMenu component.

## 5. Other information
https://www.loom.com/share/67bfdaab108c49e68dcda2c037e78a5e

2023-02-17 02:49 UTC, pnagarjun16 commented
Instead of creating the Dropdown header component separately, we only have to implement the component inside the Dropdown menu. As mentioned in this https://www.loom.com/share/917dde6b977f4ff4879da69a18d409f8

2023-02-17 05:54 UTC, pnagarjun16 requested changes

2023-02-17 21:14 UTC, pnagarjun16 commented on src/components/DropdownMenu/DropdownMenu.tsx
> +  item: string | ReactNode;
change to `item: ReactNode`

2023-02-17 21:14 UTC, pnagarjun16 commented on src/components/DropdownMenu/DropdownMenu.scss
> +      background: #381c4e;
Can we move this one to variables?

2023-02-17 21:28 UTC, pnagarjun16 commented on src/components/DropdownMenu/DropdownMenu.tsx
> +};
Can we update it like this 
```return <div className={classNames('zui-dropdown-header-container', className)} >{item}</div>```

2023-02-20 16:24 UTC, pnagarjun16 requested changes

2023-02-20 16:24 UTC, pnagarjun16 commented on src/components/DropdownMenu/DropdownMenu.tsx
> +  children?: ReactNode;
Can we change it to Header?

2023-02-20 18:22 UTC, pnagarjun16 commented on src/components/DropdownMenu/DropdownMenu.tsx
> +  children?: ReactNode;
Change it to  `children?: ReactNode;`

2023-02-20 23:19 UTC, pnagarjun16 submitted a review, later dismissed

2023-02-21 00:08 UTC, pnagarjun16 approved these changes

2023-03-02 02:10 UTC, colbr requested changes
Looks awesome @alejoviola 

Couple of requested changes, nothing major

2023-03-02 02:10 UTC, colbr commented on src/components/DropdownMenu/DropdownMenu.test.tsx
> +      expect(screen.getByText(mockText[0])).toBeInTheDocument();
Can we separate the `className` test, and just do the `toBeInDocument` one here? Just so we're testing one thing at a time.

2023-03-02 02:10 UTC, colbr commented on src/components/DropdownMenu/DropdownMenu.test.tsx
> +const renderHeader = (props?: Dropdown.HeaderProps) => render(<Dropdown.Header {...DEFAULT_PROPS_HEADER} {...props} />);
nit: brackets around function body

2023-03-02 02:10 UTC, colbr commented on src/components/DropdownMenu/DropdownMenu.tsx
> +  item: ReactNode;
Can we change `item` to `children`? This way we'll be able to use the component as `<DropdownHeader>Header Text</DropdownHeader>` - a little bit of a cleaner API. Tests will need to be updated for this

2023-03-02 02:10 UTC, colbr commented on src/components/DropdownMenu/DropdownMenu.test.tsx
> +  });
We shouldn't need to test for `Fragment` - if the component test above passes the `Fragment` one will as well.

2023-03-10 05:05 UTC, colbr approved these changes

2023-05-19 00:06 UTC, closed without merging